# CI가 끝나야지만 실행되어야 함
name: Development CD workflow

on:
  workflow_run:
    workflows: ['Development CI workflow']
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    permissions:
      packages: read
      contents: write

    steps:
      - name: Login to DockerHub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/wathing-api-dev:latest

      - name: Stop Previous Container
        run: |
          if [ "$(sudo docker ps -q -f name=wathing-api-dev)" ]; then
            sudo docker stop wathing-api-dev
          fi
        continue-on-error: true

      - name: Remove Previous Container
        run: |
          if [ "$(sudo docker ps -q -a -f name=wathing-api-dev)" ]; then
            sudo docker rm wathing-api-dev
          fi
        continue-on-error: true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
          -p 3000:3000 \
          --name wathing-api-dev \
          --env-file .env.development \
          ${{ secrets.DOCKER_USERNAME }}/wathing-api-dev:latest

      - name: Delete Dangling Images
        run: |
          dangling_images=$(sudo docker images -q -f "dangling=true")

          if [ -n "$dangling_images" ]; then
            sudo docker rmi $dangling_images
          else
            echo "붕뜬 상태의 이미지가 없습니다."
          fi
