name: Development CI workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Test
      #   run: npm run test

      # - name: Build
      #   run: npm run build

      # Dockerizing
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to DockerHub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/wathing-api-dev
          IMAGE_TAG=${IMAGE_NAME}:${{ github.sha }}
          docker build -f Dockerfile -t $IMAGE_TAG -t ${IMAGE_NAME}:latest .
          docker push $IMAGE_TAG
          docker push ${IMAGE_NAME}:latest
